### ISSUE TITLE
TypeError: locations.data.forEach is not a function

### ISSUE THREAD

**Issue by joleys** [kevinbungeneers/nhc-client#1]
I receive the following when running nhc-homekit

/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/HomeControlClient.js:90
    locations.data.forEach(function(location) {
                   ^

TypeError: locations.data.forEach is not a function
    at JsonSocket.onMessage (/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/HomeControlClient.js:90:20)
    at emitTwo (events.js:106:13)
    at JsonSocket.emit (events.js:191:7)
    at JsonSocket.onData (/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/JsonSocket.js:42:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by kevinbungeneers** [comment]
Hi!

Which version of node are you running and what's the response you get when loading the locations?

**Comment by joleys** [comment]
Node v6.9.4
NPM v3.10.10
NHC-Homekit v0.0.2

The error above is the error that shows up after running 'nhc-homekit'.  I have no other code to test the client at this point.

**Comment by kevinbungeneers** [comment]
I'll give this a look as soon as I'm able to. I'm guessing that, because I didn't add error handling yet, it's trying to parse locations from an error returned by the NHC controller.

Do you happen to know what API version your installation is at?

**Comment by joleys** [comment]
API 1.21
NHC 1.3.0.32

**Comment by ogillin** [comment]
I have the exact same issue even though I re-installed nhc-homekit from npm today.
Do you need any additional information to help you fix it?
Any additional step to perform to create locations?

API: 1.21
NHC 1.3.2.38
Node v 7.5.0
NPM 4.1.2

**Comment by kevinbungeneers** [comment]
Well, the locations are defined during the programming of your NHC installation. A possibility could be to default back to a "Main location" of some sort if no locations are defined. Problem is that I moved house and no longer have access to a NHC installation, which makes further development rather difficult.

If you feel like getting your hands dirty, I'd be more than happy to assist where possible.

**Comment by ogillin** [comment]
Hi,

Happy to be your hears and eyes testing it here.

I haven't coded in years but I'd be glad to test updates and troubleshoot
with your support.

FYI, I have Xcode but not an official developer account.

Would you have some time in the coming days ? Maybe starting with a Skype
to troubleshoot?

Olivier

**Comment by kevinbungeneers** [comment]
I'll see what I can do in the coming days or somewhere next week. You don't really need xcode, a running installation of Node should suffice!

**Comment by smiesko99** [comment]
Guys 

is this tool to get siri working whit my NHC?

how can i get it working? 

thanks

**Comment by ogillin** [comment]
@kevinbungeneers is there any chance you can have another look at this?

I just found the following. Could it help?
@openHAB 
1) http://docs.openhab.org/addons/bindings/nikohomecontrol/readme.html
2) http://docs.openhab.org/addons/io/homekit/readme.html
